# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrossplaneDocs < Formula
  desc "XDocs generator for Crossplane"
  homepage "https://github.com/Kavinraja-G/crossplane-docs/"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kavinraja-G/crossplane-docs/releases/download/v0.1.1/crossplane-docs_v0.1.1_darwin_amd64.tar.gz"
      sha256 "c0ee1b1d4719c47ccf7f79bbd349d37375767a214c972f748e3b88c9bfdef24a"

      def install
        bin.install "crossplane-docs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kavinraja-G/crossplane-docs/releases/download/v0.1.1/crossplane-docs_v0.1.1_darwin_arm64.tar.gz"
      sha256 "c41e57a8415455e98366bdd00c4ff912c45ad57c9719b7b0b71f5989273047bb"

      def install
        bin.install "crossplane-docs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/Kavinraja-G/crossplane-docs/releases/download/v0.1.1/crossplane-docs_v0.1.1_linux_amd64.tar.gz"
      sha256 "abf454fec0ec81e1e0d08d623c9c8f1e84b2a415b4800226217659d487aad56d"

      def install
        bin.install "crossplane-docs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kavinraja-G/crossplane-docs/releases/download/v0.1.1/crossplane-docs_v0.1.1_linux_arm64.tar.gz"
      sha256 "9160a79df2aef81757567600dbfa6d84bd5d94234879243141ffd2f0b184861f"

      def install
        bin.install "crossplane-docs"
      end
    end
  end
end
