# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrossplaneDocs < Formula
  desc "XDocs generator for Crossplane"
  homepage "https://github.com/Kavinraja-G/crossplane-docs/"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Kavinraja-G/crossplane-docs/releases/download/v0.1.0/crossplane-docs_v0.1.0_darwin_amd64.tar.gz"
      sha256 "50fbce16f9a0a7fdc6fa2305a2d5912b2435c46fa167c7f02fc146ecfbf77b25"

      def install
        bin.install "crossplane-docs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Kavinraja-G/crossplane-docs/releases/download/v0.1.0/crossplane-docs_v0.1.0_darwin_arm64.tar.gz"
      sha256 "6a4444107c6cbe1e68723f309e042a698b40812fe46c573da6ef190b71d8a740"

      def install
        bin.install "crossplane-docs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Kavinraja-G/crossplane-docs/releases/download/v0.1.0/crossplane-docs_v0.1.0_linux_arm64.tar.gz"
      sha256 "a359f5435949462dfb0d54c265bdd127a9b2c3c6f62fc87868b805324a6abb4e"

      def install
        bin.install "crossplane-docs"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/Kavinraja-G/crossplane-docs/releases/download/v0.1.0/crossplane-docs_v0.1.0_linux_amd64.tar.gz"
      sha256 "61ea8476944e688379ccb2234fb1d1709810494f976b419fb03438d5b4ae9f37"

      def install
        bin.install "crossplane-docs"
      end
    end
  end
end
