# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class CrossplaneDocs < Formula
  desc "XDocs generator for Crossplane"
  homepage "https://github.com/Kavinraja-G/crossplane-docs/"
  version "0.1.7"

  on_macos do
    on_intel do
      url "https://github.com/Kavinraja-G/crossplane-docs/releases/download/v0.1.7/crossplane-docs_v0.1.7_darwin_amd64.tar.gz"
      sha256 "84672d707e4feaa366812be5b04e7a7ed0de45455c885d0dc9f0c0eb251c57af"

      def install
        bin.install "crossplane-docs"
      end
    end
    on_arm do
      url "https://github.com/Kavinraja-G/crossplane-docs/releases/download/v0.1.7/crossplane-docs_v0.1.7_darwin_arm64.tar.gz"
      sha256 "77d9c9b1337d15a90f51cedf60b4cde5e9ee6403049f673a262924e8046f01f9"

      def install
        bin.install "crossplane-docs"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Kavinraja-G/crossplane-docs/releases/download/v0.1.7/crossplane-docs_v0.1.7_linux_amd64.tar.gz"
        sha256 "728ea90601c88856ec668d09e10537d7f0c69724233c507b6070ba2eac1cae50"

        def install
          bin.install "crossplane-docs"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Kavinraja-G/crossplane-docs/releases/download/v0.1.7/crossplane-docs_v0.1.7_linux_arm64.tar.gz"
        sha256 "408193e32d153e4b7f41b0a46dba669af0e1a096028947daa5f067ae9b6c1e9f"

        def install
          bin.install "crossplane-docs"
        end
      end
    end
  end
end
